<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Outward Material Issuance Register — Metonia Assembly Plant #1</title>
    @include('print.master_document_styles')
</head>
<body>

<div class="no-print" style="max-width: 900px; margin: 10px auto; text-align: right;">
    <button onclick="window.print()" style="background: #10B981; color: white; border: none; padding: 8px 16px; font-weight: bold; border-radius: 4px; cursor: pointer;">
        🖨️ Print / Save as PDF
    </button>
</div>

<div class="document-container">
    <div class="doc-watermark" style="background-image: url('{{ Qs::getSystemLogo() }}');"></div>

    @include('print.document_header', ['docRefCode' => 'ISS-REG-'.now()->format('Ymd'), 'docStatusLabel' => 'OFFICIAL REGISTER'])

    <div class="doc-title-block">
        <h2 class="doc-title">Outward Store Material Issuance Register</h2>
        <div class="doc-subtitle">{{ $outwardMovements->count() }} Dispatch Record(s) Listed</div>
    </div>

    <table class="doc-grid">
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Date</th>
                <th>Material</th>
                <th class="text-center">Quantity</th>
                <th>Vehicle / Job Card</th>
                <th>Issued By</th>
                <th>Issued To</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            @forelse($outwardMovements as $movement)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $movement->date->format('d M Y') }}</td>
                <td><strong>{{ $movement->material_name }}</strong></td>
                <td class="text-center">{{ number_format($movement->qty, 2) }} {{ $movement->unit }}</td>
                <td>{{ $movement->vehicle_label ?: 'General Stock' }}</td>
                <td>{{ $movement->issued_by ?: '—' }}</td>
                <td>{{ $movement->issued_to ?: '—' }}</td>
                <td class="font-size-sm">{{ $movement->note ?: '—' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="8" class="text-center" style="padding: 16px; color: #64748b;">No outward issuance records match this register.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="signatures-box">
        <div class="sig-line">
            <div>Prepared By</div>
            <span style="font-size: 10px; color: #64748b;">Shopkeeper / Store Attendant</span>
        </div>
        <div class="sig-line">
            <div>Verified By</div>
            <span style="font-size: 10px; color: #64748b;">Manager, Store &amp; Procurement</span>
        </div>
    </div>

    <div class="system-footer">
        Generated by <strong>Metonia Workshop Management System</strong> on {{ now()->format('d M Y, H:i') }} |
        Nairobi Assembly Plant #1
    </div>
</div>

</body>
</html>
