<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Store Inventory &amp; Raw Materials Register — Metonia Assembly Plant #1</title>
    @include('print.master_document_styles')
</head>
<body>

<div class="no-print" style="max-width: 900px; margin: 10px auto; text-align: right;">
    <button onclick="window.print()" style="background: #10B981; color: white; border: none; padding: 8px 16px; font-weight: bold; border-radius: 4px; cursor: pointer;">
        🖨️ Print / Save as PDF
    </button>
</div>

<div class="document-container">
    <div class="doc-watermark" style="background-image: url('{{ Qs::getSystemLogo() }}');"></div>

    @include('print.document_header', ['docRefCode' => 'INV-REG-'.now()->format('Ymd'), 'docStatusLabel' => 'OFFICIAL REGISTER'])

    <div class="doc-title-block">
        <h2 class="doc-title">Store Inventory &amp; Raw Materials Register</h2>
        <div class="doc-subtitle">{{ $materials->count() }} Catalog Item(s) Listed</div>
    </div>

    <table class="doc-grid">
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Item Code</th>
                <th>Material Description</th>
                <th>Category</th>
                <th class="text-center">Qty on Hand</th>
                <th class="text-center">Low-Stock Threshold</th>
                <th class="text-right">Unit Cost (KES)</th>
                <th>Supplier</th>
            </tr>
        </thead>
        <tbody>
            @forelse($materials as $material)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $material->item_code }}</td>
                <td><strong>{{ $material->name }}</strong></td>
                <td>{{ $material->category }}</td>
                <td class="text-center {{ $material->isLowStock() ? 'font-weight-bold' : '' }}">{{ number_format($material->qty, 2) }} {{ $material->unit }}</td>
                <td class="text-center">{{ number_format($material->low_stock, 2) }}</td>
                <td class="text-right">{{ number_format($material->unit_cost, 2) }}</td>
                <td>{{ $material->supplier ?: '—' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="8" class="text-center" style="padding: 16px; color: #64748b;">No materials match this register.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="signatures-box">
        <div class="sig-line">
            <div>Prepared By</div>
            <span style="font-size: 10px; color: #64748b;">Store Clerk</span>
        </div>
        <div class="sig-line">
            <div>Verified By</div>
            <span style="font-size: 10px; color: #64748b;">Manager, Store &amp; Procurement</span>
        </div>
    </div>

    <div class="system-footer">
        Generated by <strong>Metonia Workshop Management System</strong> on {{ now()->format('d M Y, H:i') }} |
        Nairobi Assembly Plant #1
    </div>
</div>

</body>
</html>
