<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportTitle }} — Metonia Assembly Plant #1</title>
    @include('print.master_document_styles')
</head>
<body>

<div class="no-print" style="max-width: 900px; margin: 10px auto; text-align: right;">
    <button onclick="window.print()" style="background: #10B981; color: white; border: none; padding: 8px 16px; font-weight: bold; border-radius: 4px; cursor: pointer;">
        🖨️ Print / Save as PDF
    </button>
</div>

<div class="document-container">
    <div class="doc-watermark" style="background-image: url('{{ Qs::getSystemLogo() }}');"></div>

    @include('print.document_header', ['docRefCode' => 'RST-REQ-'.now()->format('Ymd'), 'docStatusLabel' => 'OFFICIAL REQUISITION'])

    <div class="doc-title-block">
        <h2 class="doc-title">{{ $reportTitle }}</h2>
        <div class="doc-subtitle">{{ $items->count() }} Item(s) Below Safety Reorder Threshold</div>
    </div>

    <table class="doc-grid">
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Item Code</th>
                <th>Description</th>
                <th>Register Type</th>
                <th>Category</th>
                <th>Unit</th>
                <th class="text-center">On Hand</th>
                <th class="text-center">Reorder Level</th>
                <th class="text-center">Quantity Needed</th>
                <th>Supplier</th>
            </tr>
        </thead>
        <tbody>
            @forelse($items as $item)
            @php
                $isSafety = $item->isSafetyStock();
                $needed = max(0, (float)$item->low_stock - (float)$item->qty);
            @endphp
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $item->item_code }}</td>
                <td><strong>{{ $item->name }}</strong></td>
                <td>
                    <span style="font-weight: bold; color: {{ $isSafety ? '#dc2626' : '#059669' }};">
                        {{ $isSafety ? 'Worker Safety & PPE' : 'Store Material / Part' }}
                    </span>
                </td>
                <td>{{ $item->category }}</td>
                <td>{{ $item->unit }}</td>
                <td class="text-center" style="color: #dc2626; font-weight: bold;">
                    {{ (float)$item->qty == (int)$item->qty ? number_format($item->qty) : number_format($item->qty, 2) }}
                </td>
                <td class="text-center">
                    {{ (float)$item->low_stock == (int)$item->low_stock ? number_format($item->low_stock) : number_format($item->low_stock, 2) }}
                </td>
                <td class="text-center" style="background-color: #fef2f2; color: #b91c1c; font-weight: bold;">
                    +{{ (float)$needed == (int)$needed ? number_format($needed) : number_format($needed, 2) }} {{ $item->unit }}
                </td>
                <td>{{ $item->supplier ?: '—' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="10" class="text-center" style="padding: 16px; color: #64748b;">All items are sufficiently stocked above reorder safety limits. No restock needed.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    @include('print.document_signatures')

    <div class="system-footer">
        Generated by <strong>Metonia Workshop Management System</strong> on {{ now()->format('d M Y, H:i') }} |
        Nairobi Assembly Plant #1
    </div>
</div>

</body>
</html>
