<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Worker Safety &amp; PPE Register — Metonia Assembly Plant #1</title>
    @include('print.master_document_styles')
</head>
<body>

<div class="no-print" style="max-width: 900px; margin: 10px auto; text-align: right;">
    <button onclick="window.print()" style="background: #10B981; color: white; border: none; padding: 8px 16px; font-weight: bold; border-radius: 4px; cursor: pointer;">
        🖨️ Print / Save as PDF
    </button>
</div>

<div class="document-container">
    <div class="doc-watermark" style="background-image: url('{{ Qs::getSystemLogo() }}');"></div>

    @include('print.document_header', ['docRefCode' => 'PPE-REG-'.now()->format('Ymd'), 'docStatusLabel' => 'OFFICIAL REGISTER'])

    <div class="doc-title-block">
        <h2 class="doc-title">Worker Safety &amp; Personal Protective Equipment (PPE) Register</h2>
        <div class="doc-subtitle">{{ $materials->count() }} Safety Gear Item(s) Listed</div>
    </div>

    <table class="doc-grid">
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Item Code</th>
                <th>Equipment Description</th>
                <th>Category</th>
                <th>Unit</th>
                <th class="text-center">Qty on Hand</th>
                <th class="text-center">Reorder Level</th>
                <th class="text-center">Stock Status</th>
                <th>Supplier</th>
            </tr>
        </thead>
        <tbody>
            @forelse($materials as $material)
            @php
                $isDepleted = (float) $material->qty <= 0;
                $isLow = $material->isLowStock();
            @endphp
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $material->item_code }}</td>
                <td><strong>{{ $material->name }}</strong></td>
                <td>{{ $material->category }}</td>
                <td>{{ $material->unit }}</td>
                <td class="text-center {{ $isLow ? 'font-weight-bold' : '' }}">
                    {{ (float)$material->qty == (int)$material->qty ? number_format($material->qty) : number_format($material->qty, 2) }} {{ $material->unit }}
                </td>
                <td class="text-center">{{ (float)$material->low_stock == (int)$material->low_stock ? number_format($material->low_stock) : number_format($material->low_stock, 2) }}</td>
                <td class="text-center">
                    @if($isDepleted)
                        <span style="color: #dc2626; font-weight: bold;">Out of Stock</span>
                    @elseif($isLow)
                        <span style="color: #d97706; font-weight: bold;">Low Stock Alert</span>
                    @else
                        <span style="color: #059669; font-weight: bold;">In Stock</span>
                    @endif
                </td>
                <td>{{ $material->supplier ?: '—' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="9" class="text-center" style="padding: 16px; color: #64748b;">No safety stock items match this register.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    @include('print.document_signatures')

    <div class="system-footer">
        Generated by <strong>Metonia Workshop Management System</strong> on {{ now()->format('d M Y, H:i') }} |
        Nairobi Assembly Plant #1
    </div>
</div>

</body>
</html>
