<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Lead Supervisors Roster — Metonia Assembly Plant #1</title>
    @include('print.master_document_styles')
</head>
<body>

<div class="no-print" style="max-width: 900px; margin: 10px auto; text-align: right;">
    <button onclick="window.print()" style="background: #10B981; color: white; border: none; padding: 8px 16px; font-weight: bold; border-radius: 4px; cursor: pointer;">
        🖨️ Print / Save as PDF
    </button>
</div>

<div class="document-container">
    <div class="doc-watermark" style="background-image: url('{{ Qs::getSystemLogo() }}');"></div>

    @include('print.document_header', ['docRefCode' => 'SUP-REG-'.now()->format('Ymd'), 'docStatusLabel' => 'OFFICIAL REGISTER'])

    <div class="doc-title-block">
        <h2 class="doc-title">Workshop Lead Supervisors Roster</h2>
        <div class="doc-subtitle">{{ $supervisors->count() }} Supervisor(s) Listed</div>
    </div>

    <table class="doc-grid">
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Supervisor Name</th>
                <th>Designation</th>
                <th>Assigned Build Stage</th>
                <th>Contact Phone</th>
                <th class="text-center">Active Workload</th>
            </tr>
        </thead>
        <tbody>
            @forelse($supervisors as $supervisor)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td><strong>{{ $supervisor->name }}</strong></td>
                <td>{{ $supervisor->title }}</td>
                <td>{{ $supervisor->stage }}</td>
                <td>{{ $supervisor->phone ?: '—' }}</td>
                <td class="text-center">{{ $supervisor->activeSupervisedVehiclesCount() }} Vehicles</td>
            </tr>
            @empty
            <tr>
                <td colspan="6" class="text-center" style="padding: 16px; color: #64748b;">No supervisors are currently on the roster.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="signatures-box">
        <div class="sig-line">
            <div>Prepared By</div>
            <span style="font-size: 10px; color: #64748b;">Plant Operations Clerk</span>
        </div>
        <div class="sig-line">
            <div>Verified By</div>
            <span style="font-size: 10px; color: #64748b;">Plant Operations Director</span>
        </div>
    </div>

    <div class="system-footer">
        Generated by <strong>Metonia Workshop Management System</strong> on {{ now()->format('d M Y, H:i') }} |
        Nairobi Assembly Plant #1
    </div>
</div>

</body>
</html>
