<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Tools &amp; Equipment Asset Register — Metonia Assembly Plant #1</title>
    @include('print.master_document_styles')
</head>
<body>

<div class="no-print" style="max-width: 900px; margin: 10px auto; text-align: right;">
    <button onclick="window.print()" style="background: #10B981; color: white; border: none; padding: 8px 16px; font-weight: bold; border-radius: 4px; cursor: pointer;">
        🖨️ Print / Save as PDF
    </button>
</div>

<div class="document-container">
    <div class="doc-watermark" style="background-image: url('{{ Qs::getSystemLogo() }}');"></div>

    @include('print.document_header', ['docRefCode' => 'TL-REG-'.now()->format('Ymd'), 'docStatusLabel' => 'OFFICIAL REGISTER'])

    <div class="doc-title-block">
        <h2 class="doc-title">Workshop Tools &amp; Calibration Asset Register</h2>
        <div class="doc-subtitle">{{ $tools->count() }} Asset(s) Listed</div>
    </div>

    <table class="doc-grid">
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Asset Tag</th>
                <th>Equipment Description</th>
                <th>Category</th>
                <th class="text-center">Status</th>
                <th>Issued By</th>
                <th>Issued To</th>
            </tr>
        </thead>
        <tbody>
            @forelse($tools as $tool)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $tool->asset_tag }}</td>
                <td><strong>{{ $tool->name }}</strong></td>
                <td>{{ $tool->category }}</td>
                <td class="text-center">{{ $tool->status }}</td>
                <td>{{ $tool->issued_by ?: 'Store Supervisor' }}</td>
                <td>{{ ($tool->assigned_to && $tool->assigned_to !== 'In Tool Crib') ? $tool->assigned_to : 'In Tool Crib' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" class="text-center" style="padding: 16px; color: #64748b;">No equipment assets match this register.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="signatures-box">
        <div class="sig-line">
            <div>Prepared By</div>
            <span style="font-size: 10px; color: #64748b;">Tool Crib Supervisor</span>
        </div>
        <div class="sig-line">
            <div>Verified By</div>
            <span style="font-size: 10px; color: #64748b;">Plant Operations Director</span>
        </div>
    </div>

    <div class="system-footer">
        Generated by <strong>Metonia Workshop Management System</strong> on {{ now()->format('d M Y, H:i') }} |
        Nairobi Assembly Plant #1
    </div>
</div>

</body>
</html>
