<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Vehicle Build &amp; Job Cards Register — Metonia Assembly Plant #1</title>
    @include('print.master_document_styles')
</head>
<body>

<div class="no-print" style="max-width: 900px; margin: 10px auto; text-align: right;">
    <button onclick="window.print()" style="background: #10B981; color: white; border: none; padding: 8px 16px; font-weight: bold; border-radius: 4px; cursor: pointer;">
        🖨️ Print / Save as PDF
    </button>
</div>

<div class="document-container">
    <div class="doc-watermark" style="background-image: url('{{ Qs::getSystemLogo() }}');"></div>

    @include('print.document_header', ['docRefCode' => 'VEH-REG-'.now()->format('Ymd'), 'docStatusLabel' => 'OFFICIAL REGISTER'])

    <div class="doc-title-block">
        <h2 class="doc-title">Vehicle Build &amp; Job Cards Register</h2>
        <div class="doc-subtitle">{{ $vehicles->count() }} Vehicle(s) Listed</div>
    </div>

    <table class="doc-grid">
        <thead>
            <tr>
                <th style="width: 30px;">#</th>
                <th>Chassis / Plate</th>
                <th>Vehicle</th>
                <th>Client Account</th>
                <th>Current Stage</th>
                <th>Supervisor</th>
                <th class="text-center">Days in Stage</th>
                <th class="text-right">Invoice (KES)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($vehicles as $vehicle)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td><strong>{{ $vehicle->plate }}</strong></td>
                <td>{{ $vehicle->make }} {{ $vehicle->model }}</td>
                <td>{{ $vehicle->customer_name ?: '—' }}</td>
                <td>{{ $vehicle->stage }}</td>
                <td>{{ $vehicle->assigned_to ?: 'Unassigned' }}</td>
                <td class="text-center">{{ $vehicle->days_in_current_stage }}</td>
                <td class="text-right">{{ number_format($vehicle->invoice_total, 2) }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="8" class="text-center" style="padding: 16px; color: #64748b;">No vehicles match this register.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="signatures-box">
        <div class="sig-line">
            <div>Prepared By</div>
            <span style="font-size: 10px; color: #64748b;">Plant Operations Clerk</span>
        </div>
        <div class="sig-line">
            <div>Verified By</div>
            <span style="font-size: 10px; color: #64748b;">Plant Operations Director</span>
        </div>
    </div>

    <div class="system-footer">
        Generated by <strong>Metonia Workshop Management System</strong> on {{ now()->format('d M Y, H:i') }} |
        Nairobi Assembly Plant #1
    </div>
</div>

</body>
</html>
